const data = [
    {
        index: 1,
        color: '#e7ff8f',
        href: 'https://en.m.wikipedia.org/wiki/Hydrogen',
        name: 'hydrogen',
        symbol: 'H'
      }, {
        index: 2,
        color: '#c0ffff',
        href: 'https://en.m.wikipedia.org/wiki/Helium',
        name: 'helium',
        symbol: 'He'
      }, {
        index: 3,
        color: '#ff6666',
        href: 'https://en.m.wikipedia.org/wiki/Lithium',
        name: 'lithium',
        symbol: 'Li'
      }, {
        index: 4,
        color: '#ffdead',
        href: 'https://en.m.wikipedia.org/wiki/Beryllium',
        name: 'beryllium',
        symbol: 'Be'
      }, {
        index: 5,
        color: '#cccc99',
        href: 'https://en.m.wikipedia.org/wiki/Boron',
        name: 'boron',
        symbol: 'B'
      }, {
        index: 6,
        color: '#a1ffc3',
        href: 'https://en.m.wikipedia.org/wiki/Carbon',
        name: 'carbon',
        symbol: 'C'
      }, {
        index: 7,
        color: '#e7ff8f',
        href: 'https://en.m.wikipedia.org/wiki/Nitrogen',
        name: 'nitrogen',
        symbol: 'N'
      }, {
        index: 8,
        color: '#e7ff8f',
        href: 'https://en.m.wikipedia.org/wiki/Oxygen',
        name: 'oxygen',
        symbol: 'O'
      }, {
        index: 9,
        color: '#e7ff8f',
        href: 'https://en.m.wikipedia.org/wiki/Fluorine',
        name: 'fluorine',
        symbol: 'F'
      }, {
        index: 10,
        color: '#c0ffff',
        href: 'https://en.m.wikipedia.org/wiki/Neon',
        name: 'neon',
        symbol: 'Ne'
      }, {
        index: 11,
        color: '#ff6666',
        href: 'https://en.m.wikipedia.org/wiki/Sodium',
        name: 'sodium',
        symbol: 'Na'
      }, {
        index: 12,
        color: '#ffdead',
        href: 'https://en.m.wikipedia.org/wiki/Magnesium',
        name: 'magnesium',
        symbol: 'Mg'
      }, {
        index: 13,
        color: '#cccccc',
        href: 'https://en.m.wikipedia.org/wiki/Aluminium',
        name: 'aluminium',
        symbol: 'Al'
      }, {
        index: 14,
        color: '#cccc99',
        href: 'https://en.m.wikipedia.org/wiki/Silicon',
        name: 'silicon',
        symbol: 'Si'
      }, {
        index: 15,
        color: '#a1ffc3',
        href: 'https://en.m.wikipedia.org/wiki/Phosphorus',
        name: 'phosphorus',
        symbol: 'P'
      }, {
        index: 16,
        color: '#a1ffc3',
        href: 'https://en.m.wikipedia.org/wiki/Sulfur',
        name: 'sulfur',
        symbol: 'S'
      }, {
        index: 17,
        color: '#e7ff8f',
        href: 'https://en.m.wikipedia.org/wiki/Chlorine',
        name: 'chlorine',
        symbol: 'Cl'
      }, {
        index: 18,
        color: '#c0ffff',
        href: 'https://en.m.wikipedia.org/wiki/Argon',
        name: 'argon',
        symbol: 'Ar'
      }, {
        index: 19,
        color: '#ff6666',
        href: 'https://en.m.wikipedia.org/wiki/Potassium',
        name: 'potassium',
        symbol: 'K'
      }, {
        index: 20,
        color: '#ffdead',
        href: 'https://en.m.wikipedia.org/wiki/Calcium',
        name: 'calcium',
        symbol: 'Ca'
      }, {
        index: 21,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Scandium',
        name: 'scandium',
        symbol: 'Sc'
      }, {
        index: 22,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Titanium',
        name: 'titanium',
        symbol: 'Ti'
      }, {
        index: 23,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Vanadium',
        name: 'vanadium',
        symbol: 'V'
      }, {
        index: 24,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Chromium',
        name: 'chromium',
        symbol: 'Cr'
      }, {
        index: 25,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Manganese',
        name: 'manganese',
        symbol: 'Mn'
      }, {
        index: 26,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Iron',
        name: 'iron',
        symbol: 'Fe'
      }, {
        index: 27,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Cobalt',
        name: 'cobalt',
        symbol: 'Co'
      }, {
        index: 28,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Nickel',
        name: 'nickel',
        symbol: 'Ni'
      }, {
        index: 29,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Copper',
        name: 'copper',
        symbol: 'Cu'
      }, {
        index: 30,
        color: '#ffc0c0',
        href: 'https://en.m.wikipedia.org/wiki/Zinc',
        name: 'zinc',
        symbol: 'Zn'
      }, {
        index: 31,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Gallium",
        name: "gallium",
        symbol: "Ga"
    }, {
        index: 32,
        color: "#cccc99",
        href: "https://en.m.wikipedia.org/wiki/Germanium",
        name: "germanium",
        symbol: "Ge"
    }, {
        index: 33,
        color: "#cccc99",
        href: "https://en.m.wikipedia.org/wiki/Arsenic",
        name: "arsenic",
        symbol: "As"
    }, {
        index: 34,
        color: "#a1ffc3",
        href: "https://en.m.wikipedia.org/wiki/Selenium",
        name: "selenium",
        symbol: "Se"
    }, {
        index: 35,
        color: "#e7ff8f",
        href: "https://en.m.wikipedia.org/wiki/Bromine",
        name: "bromine",
        symbol: "Br"
    }, {
        index: 36,
        color: "#c0ffff",
        href: "https://en.m.wikipedia.org/wiki/Krypton",
        name: "krypton",
        symbol: "Kr"
    }, {
        index: 37,
        color: "#ff6666",
        href: "https://en.m.wikipedia.org/wiki/Rubidium",
        name: "rubidium",
        symbol: "Rb"
    }, {
        index: 38,
        color: "#ffdead",
        href: "https://en.m.wikipedia.org/wiki/Strontium",
        name: "strontium",
        symbol: "Sr"
    }, {
        index: 39,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Yttrium",
        name: "yttrium",
        symbol: "Y"
    }, {
        index: 40,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Zirconium",
        name: "zirconium",
        symbol: "Zr"
    }, {
        index: 41,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Niobium",
        name: "niobium",
        symbol: "Nb"
    }, {
        index: 42,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Molybdenum",
        name: "molybdenum",
        symbol: "Mo"
    }, {
        index: 43,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Technetium",
        name: "technetium",
        symbol: "Tc"
    }, {
        index: 44,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Ruthenium",
        name: "ruthenium",
        symbol: "Ru"
    }, {
        index: 45,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Rhodium",
        name: "rhodium",
        symbol: "Rh"
    }, {
        index: 46,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Palladium",
        name: "palladium",
        symbol: "Pd"
    }, {
        index: 47,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Silver",
        name: "silver",
        symbol: "Ag"
    }, {
        index: 48,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Cadmium",
        name: "cadmium",
        symbol: "Cd"
    }, {
        index: 49,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Indium",
        name: "indium",
        symbol: "In"
    }, {
        index: 50,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Tin",
        name: "tin",
        symbol: "Sn"
    }, {
        index: 51,
        color: "#cccc99",
        href: "https://en.m.wikipedia.org/wiki/Antimony",
        name: "antimony",
        symbol: "Sb"
    }, {
        index: 52,
        color: "#cccc99",
        href: "https://en.m.wikipedia.org/wiki/Tellurium",
        name: "tellurium",
        symbol: "Te"
    }, {
        index: 53,
        color: "#e7ff8f",
        href: "https://en.m.wikipedia.org/wiki/Iodine",
        name: "iodine",
        symbol: "I"
    }, {
        index: 54,
        color: "#c0ffff",
        href: "https://en.m.wikipedia.org/wiki/Xenon",
        name: "xenon",
        symbol: "Xe"
    }, {
        index: 55,
        color: "#ff6666",
        href: "https://en.m.wikipedia.org/wiki/Caesium",
        name: "caesium",
        symbol: "Cs"
    }, {
        index: 56,
        color: "#ffdead",
        href: "https://en.m.wikipedia.org/wiki/Barium",
        name: "barium",
        symbol: "Ba"
    }, {
        index: 57,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Lanthanum",
        name: "lanthanum",
        symbol: "La"
    }, {
        index: 58,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Cerium",
        name: "cerium",
        symbol: "Ce"
    }, {
        index: 59,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Praseodymium",
        name: "praseodymium",
        symbol: "Pr"
    }, {
        index: 60,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Neodymium",
        name: "neodymium",
        symbol: "Nd"
    }, {
        index: 61,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Promethium",
        name: "promethium",
        symbol: "Pm"
    }, {
        index: 62,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Samarium",
        name: "samarium",
        symbol: "Sm"
    }, {
        index: 63,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Europium",
        name: "europium",
        symbol: "Eu"
    }, {
        index: 64,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Gadolinium",
        name: "gadolinium",
        symbol: "Gd"
    }, {
        index: 65,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Terbium",
        name: "terbium",
        symbol: "Tb"
    }, {
        index: 66,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Dysprosium",
        name: "dysprosium",
        symbol: "Dy"
    }, {
        index: 67,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Holmium",
        name: "holmium",
        symbol: "Ho"
    }, {
        index: 68,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Erbium",
        name: "erbium",
        symbol: "Er"
    }, {
        index: 69,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Thulium",
        name: "thulium",
        symbol: "Tm"
    }, {
        index: 70,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Ytterbium",
        name: "ytterbium",
        symbol: "Yb"
    }, {
        index: 71,
        color: "#ffbfff",
        href: "https://en.m.wikipedia.org/wiki/Lutetium",
        name: "lutetium",
        symbol: "Lu"
    }, {
        index: 72,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Hafnium",
        name: "hafnium",
        symbol: "Hf"
    }, {
        index: 73,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Tantalum",
        name: "tantalum",
        symbol: "Ta"
    }, {
        index: 74,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Tungsten",
        name: "tungsten",
        symbol: "W"
    }, {
        index: 75,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Rhenium",
        name: "rhenium",
        symbol: "Re"
    }, {
        index: 76,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Osmium",
        name: "osmium",
        symbol: "Os"
    }, {
        index: 77,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Iridium",
        name: "iridium",
        symbol: "Ir"
    }, {
        index: 78,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Platinum",
        name: "platinum",
        symbol: "Pt"
    }, {
        index: 79,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Gold",
        name: "gold",
        symbol: "Au"
    }, {
        index: 80,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Mercury_(element)",
        name: "mercury",
        symbol: "Hg"
    }, {
        index: 81,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Thallium",
        name: "thallium",
        symbol: "Tl"
    }, {
        index: 82,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Lead",
        name: "lead",
        symbol: "Pb"
    }, {
        index: 83,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Bismuth",
        name: "bismuth",
        symbol: "Bi"
    }, {
        index: 84,
        color: "#cccccc",
        href: "https://en.m.wikipedia.org/wiki/Polonium",
        name: "polonium",
        symbol: "Po"
    }, {
        index: 85,
        color: "#cccc99",
        href: "https://en.m.wikipedia.org/wiki/Astatine",
        name: "astatine",
        symbol: "At"
    }, {
        index: 86,
        color: "#c0ffff",
        href: "https://en.m.wikipedia.org/wiki/Radon",
        name: "radon",
        symbol: "Rn"
    }, {
        index: 87,
        color: "#ff6666",
        href: "https://en.m.wikipedia.org/wiki/Francium",
        name: "francium",
        symbol: "Fr"
    }, {
        index: 88,
        color: "#ffdead",
        href: "https://en.m.wikipedia.org/wiki/Radium",
        name: "radium",
        symbol: "Ra"
    }, {
        index: 89,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Actinium",
        name: "actinium",
        symbol: "Ac"
    }, {
        index: 90,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Thorium",
        name: "thorium",
        symbol: "Th"
    }, {
        index: 91,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Protactinium",
        name: "protactinium",
        symbol: "Pa"
    }, {
        index: 92,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Uranium",
        name: "uranium",
        symbol: "U"
    }, {
        index: 93,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Neptunium",
        name: "neptunium",
        symbol: "Np"
    }, {
        index: 94,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Plutonium",
        name: "plutonium",
        symbol: "Pu"
    }, {
        index: 95,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Americium",
        name: "americium",
        symbol: "Am"
    }, {
        index: 96,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Curium",
        name: "curium",
        symbol: "Cm"
    }, {
        index: 97,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Berkelium",
        name: "berkelium",
        symbol: "Bk"
    }, {
        index: 98,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Californium",
        name: "californium",
        symbol: "Cf"
    }, {
        index: 99,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Einsteinium",
        name: "einsteinium",
        symbol: "Es"
    }, {
        index: 100,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Fermium",
        name: "fermium",
        symbol: "Fm"
    }, {
        index: 101,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Mendelevium",
        name: "mendelevium",
        symbol: "Md"
    }, {
        index: 102,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Nobelium",
        name: "nobelium",
        symbol: "No"
    }, {
        index: 103,
        color: "#ff99cc",
        href: "https://en.m.wikipedia.org/wiki/Lawrencium",
        name: "lawrencium",
        symbol: "Lr"
    }, {
        index: 104,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Rutherfordium",
        name: "rutherfordium",
        symbol: "Rf"
    }, {
        index: 105,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Dubnium",
        name: "dubnium",
        symbol: "Db"
    }, {
        index: 106,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Seaborgium",
        name: "seaborgium",
        symbol: "Sg"
    }, {
        index: 107,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Bohrium",
        name: "bohrium",
        symbol: "Bh"
    }, {
        index: 108,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Hassium",
        name: "hassium",
        symbol: "Hs"
    }, {
        index: 109,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Meitnerium",
        name: "meitnerium",
        symbol: "Mt"
    }, {
        index: 110,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Darmstadtium",
        name: "darmstadtium",
        symbol: "Ds"
    }, {
        index: 111,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Roentgenium",
        name: "roentgenium",
        symbol: "Rg"
    }, {
        index: 112,
        color: "#ffc0c0",
        href: "https://en.m.wikipedia.org/wiki/Copernicium",
        name: "copernicium",
        symbol: "Cn"
    }, {
        index: 113,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Nihonium",
        name: "nihonium",
        symbol: "Nh"
    }, {
        index: 114,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Flerovium",
        name: "flerovium",
        symbol: "Fl"
    }, {
        index: 115,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Moscovium",
        name: "moscovium",
        symbol: "Mc"
    }, {
        index: 116,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Livermorium",
        name: "livermorium",
        symbol: "Lv"
    }, {
        index: 117,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Tennessine",
        name: "tennessine",
        symbol: "Ts"
    }, {
        index: 118,
        color: "#e8e8e8",
        href: "https://en.m.wikipedia.org/wiki/Oganesson",
        name: "oganesson",
        symbol: "Og"
    }
]

export default data;
